# California Housing Market : Feature engineering and feature selection
In the previous exercise, we concluded it was worth including more variables in a model. But is this set of variables **the best** we could have chosen ? In this exercises, we'll go further by applying two canonical methods:
* Feature engineering consists in creating more variables from the original dataset
* Feature selection allows to select the best set of features among all the available variables

## The dataset
1. Load the California Housing dataset again and remove the outliers:

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import  OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
# setting Jedha color palette as default
pio.templates["jedha"] = go.layout.Template(
    layout_colorway=["#4B9AC7", "#4BE8E0", "#9DD4F3", "#97FBF6", "#2A7FAF", "#23B1AB", "#0E3449", "#015955"]
)
pio.templates.default = "jedha"
pio.renderers.default = "svg" # to be replaced by "iframe" if working on JULIE

In [2]:
from sklearn import datasets
data = datasets.fetch_california_housing(data_home=None, download_if_missing=True, return_X_y=False)
print(data.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33 (1997) 291-297

In [4]:
data_pd = pd.DataFrame(data=data.data, columns=data.feature_names)
data_pd["Price"] = pd.DataFrame(data=data.target)
data_pd.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [5]:
mask_outliers = (data_pd["AveRooms"] < 10) & (data_pd["AveBedrms"] < 10) & (data_pd["Population"] < 15000) & (data_pd["AveOccup"] < 10) & (data_pd["Price"] < 5)
data_filtered = data_pd[mask_outliers]
data_filtered.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [6]:
print("Number orf rows:", len(data_filtered))
print()
print("Display of dataset:")
print(data_filtered.head())
print()
print("Basics statistics:")
print(data_filtered.describe())
print()
print("Percentage of missing values:")
perc = 100 * data_filtered.isnull().sum()/ len(data_filtered)
print(perc)

Number orf rows: 19398

Display of dataset:
   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85

   Longitude  Price
0    -122.23  4.526
1    -122.22  3.585
2    -122.24  3.521
3    -122.25  3.413
4    -122.25  3.422

Basics statistics:
             MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  19398.000000  19398.000000  19398.000000  19398.000000  19398.000000
mean       3.674497     28.496907      5.210648      1.066038   1442.172080
std        1.563397     12.477953      1.168098      0.128846   1077.498768
min        0.499900      1.000000      0.846154      0.333333      3.000000
25%        2.525900     18.000000      4.407329      1.005413    805.000000
50%        3.447800     29.000000      5.170038      1.047619   1185.500000
75%        4.583175     37.000000      5.944617      1.096884   1752.000000
max       15.000100     52.000000      9.979167      3.411111  13251.000000

           AveOccup      Latitude     Longitude         Price
count  19398.000000  19398.000000  19398.000000  19398.000000
mean       2.944640     35.637872   -119.567484      1.924128
std        0.766194      2.142960      2.004793      0.971784
min        0.750000     32.540000   -124.350000      0.149990
25%        2.450413     33.930000   -121.770000      1.167000
50%        2.842105     34.260000   -118.490000      1.741000
75%        3.308127     37.720000   -118.000000      2.485000
max        9.954545     41.950000   -114.550000      4.991000

Percentage of missing values:
MedInc        0.0
HouseAge      0.0
AveRooms      0.0
AveBedrms     0.0
Population    0.0
AveOccup      0.0
Latitude      0.0
Longitude     0.0
Price         0.0
dtype: float64

2. Separate the target from the features

In [9]:
# Separate target variable Y from features X
print("Separating labels from features...")
features_list = ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude']
target_variable = "Price"

X = data_filtered.loc[:,features_list]
Y = data_filtered.loc[:,target_variable]

print("...Done.")
print()

print('Y : ')
print(Y.head())
print()
print('X :')
print(X.head())

Separating labels from features...
...Done.

Y :
0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
Name: Price, dtype: float64

X :
   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85

   Longitude
0    -122.23
1    -122.22
2    -122.24
3    -122.25
4    -122.25

## From linear to non-linear regression
An easy way of implementing a non-linear regression is to create by hand more columns containing non-linear functions of the features.

3. For each explanatory variable, create 3 new columns in $X$ containing the following functions:
* $\textrm{X}^2$
* $\textrm{X}^3$
* $\textrm{X}^4$
* $\frac{1}{\textrm{X}}$
* $\frac{1}{\textrm{X}^2}$

In [10]:
for col in features_list:
    data_filtered[f'{col}_2'] = data_filtered[col] ** 2
    data_filtered[f'{col}_3'] = data_filtered[col] ** 3
    data_filtered[f'{col}_4'] = data_filtered[col] ** 4
    data_filtered[f'{col}_inverse'] = 1 / data_filtered[col]
    data_filtered[f'{col}_inverse2'] = 1 / (data_filtered[col] ** 2)

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\3810268415.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
data_filtered.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price,MedInc_2,...,Latitude_2,Latitude_3,Latitude_4,Latitude_inverse,Latitude_inverse2,Longitude_2,Longitude_3,Longitude_4,Longitude_inverse,Longitude_inverse2
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526,69.308955,...,1434.8944,54353.799872,2.058922e+06,0.026399,0.000697,14940.1729,-1.826137e+06,2.232088e+08,-0.008181,0.000067
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585,68.913242,...,1433.3796,54267.751656,2.054577e+06,0.026413,0.000698,14937.7284,-1.825689e+06,2.231357e+08,-0.008182,0.000067
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521,52.669855,...,1432.6225,54224.761625,2.052407e+06,0.026420,0.000698,14942.6176,-1.826586e+06,2.232818e+08,-0.008181,0.000067
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413,31.844578,...,1432.6225,54224.761625,2.052407e+06,0.026420,0.000698,14945.0625,-1.827034e+06,2.233549e+08,-0.008180,0.000067
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422,14.793254,...,1432.6225,54224.761625,2.052407e+06,0.026420,0.000698,14945.0625,-1.827034e+06,2.233549e+08,-0.008180,0.000067

4. Split your dataset into train (80%) and test (20%)

In [22]:
# Separate target variable Y from features X
print("Separating labels from features...")
features_list = data_filtered.drop("Price", axis=1).columns.tolist()
target_variable = "Price"

X = data_filtered.loc[:,features_list]
Y = data_filtered.loc[:,target_variable]

print("...Done.")
print()

print('Y : ')
print(Y.head())
print()
print('X :')
print(X.head())

Separating labels from features...
...Done.

Y :
0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
Name: Price, dtype: float64

X :
   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85

   Longitude   MedInc_2    MedInc_3  ...  Latitude_2    Latitude_3  \
0    -122.23  69.308955  577.010912  ...   1434.8944  54353.799872
1    -122.22  68.913242  572.076387  ...   1433.3796  54267.751656
2    -122.24  52.669855  382.246204  ...   1432.6225  54224.761625
3    -122.25  31.844578  179.702136  ...   1432.6225  54224.761625
4    -122.25  14.793254   56.897815  ...   1432.6225  54224.761625

     Latitude_4  Latitude_inverse  Latitude_inverse2  Longitude_2  \
0  2.058922e+06          0.026399           0.000697   14940.1729
1  2.054577e+06          0.026413           0.000698   14937.7284
2  2.052407e+06          0.026420           0.000698   14942.6176
3  2.052407e+06          0.026420           0.000698   14945.0625
4  2.052407e+06          0.026420           0.000698   14945.0625

    Longitude_3   Longitude_4  Longitude_inverse  Longitude_inverse2
0 -1.826137e+06  2.232088e+08          -0.008181            0.000067
1 -1.825689e+06  2.231357e+08          -0.008182            0.000067
2 -1.826586e+06  2.232818e+08          -0.008181            0.000067
3 -1.827034e+06  2.233549e+08          -0.008180            0.000067
4 -1.827034e+06  2.233549e+08          -0.008180            0.000067

[5 rows x 48 columns]

In [23]:
# Divide dataset Train set & Test set 
print("Dividing into train and test sets...")
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
print("...Done.")
print()

Dividing into train and test sets...
...Done.

5. Apply the same preprocessing as in the previous exercise

In [24]:
print("Preprocessing X_train...")
print(X_train.head())
print()
preprocessor = Pipeline(steps=[
    ('scaler', StandardScaler())
])
X_train = preprocessor.fit_transform(X_train)
print("...Done!")
print(X_train[0:5,:]) # X_train is now a numpy array
print()

Preprocessing X_train...
       MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
3235   2.3889       6.0  6.316614   1.294671       992.0  3.109718     36.09
13981  3.4912       7.0  8.355308   1.554795      2933.0  2.511130     34.85
9219   1.9464      36.0  4.975510   1.053061       639.0  2.608163     37.12
10851  3.1667      22.0  3.803838   1.000000      1952.0  2.081023     33.66
8888   4.2520      31.0  3.978296   1.039389      1985.0  1.595659     34.03

       Longitude   MedInc_2   MedInc_3  ...  Latitude_2    Latitude_3  \
3235     -119.57   5.706843  13.633078  ...   1302.4881  47006.795529
13981    -117.46  12.188477  42.552412  ...   1214.5225  42326.109125
9219     -120.27   3.788473   7.373884  ...   1377.8944  51147.440128
10851    -117.90  10.027989  31.755632  ...   1132.9956  38136.631896
8888     -118.49  18.079504  76.874051  ...   1158.0409  39408.131827

         Latitude_4  Latitude_inverse  Latitude_inverse2  Longitude_2  \
3235   1.696475e+06          0.027709           0.000768   14296.9849
13981  1.475065e+06          0.028694           0.000823   13796.8516
9219   1.898593e+06          0.026940           0.000726   14464.8729
10851  1.283679e+06          0.029709           0.000883   13900.4100
8888   1.341059e+06          0.029386           0.000864   14039.8801

        Longitude_3   Longitude_4  Longitude_inverse  Longitude_inverse2
3235  -1.709490e+06  2.044038e+08          -0.008363            0.000070
13981 -1.620578e+06  1.903531e+08          -0.008514            0.000072
9219  -1.739690e+06  2.092325e+08          -0.008315            0.000069
10851 -1.638858e+06  1.932214e+08          -0.008482            0.000072
8888  -1.663585e+06  1.971182e+08          -0.008440            0.000071

[5 rows x 48 columns]

...Done!
[[-8.19927084e-01 -1.80892400e+00  9.55328430e-01  1.78190047e+00
  -4.16134941e-01  2.18006083e-01  2.11764744e-01 -2.73283112e-03
  -7.23284862e-01 -5.55080709e-01 -3.80952185e-01  5.13008216e-01
   1.82695953e-01 -1.26498533e+00 -9.49143480e-01 -7.60926697e-01
   2.46604354e+00  1.09423468e+00  9.05288599e-01  8.03814419e-01
   6.69053879e-01 -8.33507043e-01 -6.12210207e-01  1.45391405e+00
   1.00467627e+00  5.75774220e-01 -1.89314156e+00 -1.63270329e+00
  -3.05939544e-01 -1.69174011e-01 -9.87311791e-02 -7.12692942e-02
  -2.04111800e-02  7.67587648e-02 -3.41707972e-02 -8.53015365e-02
  -4.40113786e-01 -4.73219971e-01  1.80503284e-01  1.49155312e-01
   1.17863833e-01 -2.73488382e-01 -3.03698049e-01 -5.61484636e-03
   1.39454572e-02 -2.22561768e-02  1.94679289e-02 -2.78495433e-02]
 [-1.12594285e-01 -1.72879039e+00  2.70646520e+00  3.80387675e+00
   1.40114366e+00 -5.61637519e-01 -3.67622089e-01  1.05246805e+00
  -2.62141004e-01 -3.10620943e-01 -2.74973750e-01 -2.65306230e-01
  -2.83619984e-01 -1.24741974e+00 -9.45845287e-01 -7.60362987e-01
   1.96672692e+00  7.45073583e-01  3.26850856e+00  3.77972789e+00
   4.19399159e+00 -1.55246631e+00 -9.56925512e-01  3.50865239e+00
   2.78195771e+00  1.86697024e+00 -3.27882867e+00 -2.58813351e+00
   7.43881852e-01  2.21042406e-01  1.76449119e-02 -2.25648180e-01
  -2.13585561e-02 -5.33045492e-01 -4.27860803e-01 -2.89717698e-01
   4.03652832e-01  2.60892706e-01 -3.88044989e-01 -4.07351745e-01
  -4.25444967e-01  3.23827337e-01  3.00657881e-01 -1.04888652e+00
   1.04525437e+00 -1.04157365e+00 -1.05947081e+00  1.06288768e+00]
 [-1.10387407e+00  5.95084207e-01 -1.96613519e-01 -9.61635976e-02
  -7.46634346e-01 -4.35254612e-01  6.93029614e-01 -3.52799474e-01
  -8.59769679e-01 -6.07990677e-01 -3.97595329e-01  1.07342507e+00
   6.26727101e-01  4.37526139e-01  2.56904104e-01  9.52600265e-02
  -4.46636708e-01 -1.85276619e-01 -2.91185513e-01 -3.53787141e-01
  -3.82679154e-01 -3.92891472e-02 -1.20046672e-01 -1.18532973e-01
  -1.16790980e-01 -9.65102839e-02  7.14415544e-03 -3.88173782e-02
  -3.85277113e-01 -1.80681447e-01 -1.00008571e-01  5.75996517e-02
  -1.89028085e-02 -4.43014745e-01 -3.75116411e-01 -2.64955433e-01
   2.40572805e-01  1.06816507e-01  6.67877004e-01  6.41454463e-01
   6.13831348e-01 -7.39304271e-01 -7.60341444e-01  3.44597377e-01
  -3.36346945e-01  3.28051163e-01  3.69046705e-01 -3.77085853e-01]
 [-3.20822075e-01 -5.26786290e-01 -1.20302182e+00 -5.08615628e-01
   4.82673641e-01 -1.12183932e+00 -9.23646549e-01  8.32426160e-01
  -4.15851626e-01 -4.01887853e-01 -3.18828885e-01 -9.24595537e-02
  -1.95163473e-01 -6.59647921e-01 -6.78224263e-01 -6.42083295e-01
  -7.59319495e-02 -1.23944672e-01 -1.10389164e+00 -9.65869120e-01
  -8.16083395e-01  1.11295801e+00  8.01812074e-01 -4.20522882e-01
  -3.04516180e-01 -1.94276966e-01  5.47452051e-01  4.74271237e-01
   8.35172295e-02 -6.52201289e-02 -7.71399932e-02 -1.85996350e-01
  -2.12046505e-02 -8.91021067e-01 -6.16512753e-01 -3.69609622e-01
   1.30962474e+00  1.22319982e+00 -9.14977997e-01 -9.05456817e-01
  -8.95078073e-01  9.38440688e-01  9.44569688e-01 -8.32865022e-01
   8.33219788e-01 -8.33491508e-01 -8.31291937e-01  8.30594457e-01]
 [ 3.75602027e-01  1.94416173e-01 -1.05317117e+00 -2.02439111e-01
   5.13570186e-01 -1.75401259e+00 -7.50764994e-01  5.37369990e-01
   1.56983344e-01 -2.04946370e-02 -1.12056174e-01 -5.67114060e-01
  -4.17401511e-01 -1.51257206e-02 -1.81080230e-01 -2.90458133e-01
  -3.52679281e-01 -1.72532861e-01 -9.96627544e-01 -8.94670953e-01
  -7.71902154e-01  8.98387217e-01  6.11500015e-01 -1.97838864e-01
  -1.67025046e-01 -1.23162844e-01  1.41088055e-01  8.59063564e-02
   1.01420385e-01 -5.90481832e-02 -7.55354671e-02 -1.87967228e-01
  -2.12137601e-02 -1.21445439e+00 -7.53373793e-01 -4.16278116e-01
   2.91854846e+00  3.37649337e+00 -7.53102650e-01 -7.54282690e-01
  -7.54276641e-01  7.42737642e-01  7.37110170e-01 -5.41932175e-01
   5.46406461e-01 -5.50792249e-01 -5.27984496e-01  5.23162565e-01]]

In [25]:
# Test pipeline
print("Preprocessing X_test...")
print(X_test.head())
print()
X_test = preprocessor.transform(X_test)
print("...Done!")
print(X_test[0:5,:]) # X_test is now a numpy array
print()

Preprocessing X_test...
       MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
17333  5.2990      12.0  7.214932   1.047511      1200.0  2.714932     34.91
1012   2.6667      44.0  4.541284   1.027523       277.0  2.541284     37.68
5124   1.5521      30.0  3.850679   1.002262      1966.0  4.447964     33.99
1845   6.3538      49.0  6.293886   1.017751      1148.0  2.264300     37.90
4035   3.2154      20.0  4.133444   1.060181      7450.0  1.772122     34.17

       Longitude   MedInc_2    MedInc_3  ...  Latitude_2    Latitude_3  \
17333    -120.44  28.079401  148.792746  ...   1218.7081  42545.099771
1012     -121.77   7.111289   18.963674  ...   1419.7824  53497.400832
5124     -118.26   2.409014    3.739031  ...   1155.3201  39269.330199
1845     -122.28  40.370774  256.507827  ...   1436.4100  54439.939000
4035     -118.52  10.338797   33.243368  ...   1167.5889  39896.512713

         Latitude_4  Latitude_inverse  Latitude_inverse2  Longitude_2  \
17333  1.485249e+06          0.028645           0.000821   14505.7936
1012   2.015782e+06          0.026539           0.000704   14827.9329
5124   1.334765e+06          0.029420           0.000866   13985.4276
1845   2.063274e+06          0.026385           0.000696   14952.3984
4035   1.363264e+06          0.029265           0.000856   14046.9904

        Longitude_3   Longitude_4  Longitude_inverse  Longitude_inverse2
17333 -1.747078e+06  2.104180e+08          -0.008303            0.000069
1012  -1.805597e+06  2.198676e+08          -0.008212            0.000067
5124  -1.653917e+06  1.955922e+08          -0.008456            0.000072
1845  -1.828379e+06  2.235742e+08          -0.008178            0.000067
4035  -1.664849e+06  1.973179e+08          -0.008437            0.000071

[5 rows x 48 columns]

...Done!
[[ 1.04744947 -1.32812236  1.72693875 -0.13930381 -0.22139308 -0.29619119
  -0.33958724 -0.43781566  0.86843834  0.5874456   0.30968356 -0.84075904
  -0.5159755  -1.11905578 -0.90987681 -0.75100948  0.71843539  0.10718311
   1.86566728  1.9136803   1.86970038 -1.20037727 -0.80008105 -0.15085042
  -0.13734077 -0.10745539  0.06109415  0.01122288 -0.24311142 -0.15707881
  -0.09697008 -0.11170421 -0.02074989 -0.34000705 -0.31236615 -0.23432195
   0.07460051 -0.04399513 -0.36099219 -0.381315   -0.40045361  0.29394803
   0.2699244   0.42995743 -0.42203602  0.41405428  0.45333115 -0.46098272]
 [-0.64166613  1.23615306 -0.56959193 -0.29467615 -1.08556008 -0.52236244
   0.95468818 -1.10294228 -0.62336384 -0.51002032 -0.3645038   0.25621231
   0.00951432  1.30229387  1.25747691  1.15048496 -0.55255235 -0.19736173
  -0.61767668 -0.61894617 -0.58410907  0.31839396  0.13978309 -0.26582877
  -0.20956556 -0.14545784  0.26022794  0.19821476 -0.4309706  -0.18453718
  -0.10026486  0.53087518 -0.00776121 -0.50543281 -0.41189701 -0.28232257
   0.35163994  0.21111713  0.93861181  0.92085146  0.90139632 -0.9818765
  -0.99304936  1.1019359  -1.10081496  1.09957975  1.10461025 -1.10527128]
 [-1.35689169  0.11428257 -1.16278792 -0.49102935  0.49578127  1.96103359
  -0.76945489  0.65239189 -0.95791296 -0.63871667 -0.40540653  1.84202965
   1.38311784 -0.0975489  -0.25356255 -0.34837031 -0.3301295  -0.16919133
  -1.07556422 -0.94737757 -0.80480034  1.05343787  0.74816593 -0.40796513
  -0.29690478 -0.19041277  0.52324656  0.45071769  0.09107585 -0.06262699
  -0.07646913 -0.18684056 -0.02120857  1.90985526  1.56764567  1.04760426
  -1.50508639 -1.17657331 -0.770688   -0.77078542 -0.76972167  0.76368932
   0.75921207 -0.65551939  0.65855566 -0.66150072 -0.64586306  0.64246175]
 [ 1.72430209  1.6368211   0.9358055  -0.37063099 -0.27007855 -0.88312705
   1.05748262 -1.35799084  1.74292326  1.49797843  1.07840409 -1.02524811
  -0.57023635  1.93060168  2.10059351  2.17929714 -0.60118709 -0.20210127
   0.8826435   0.77946155  0.64457406 -0.82286628 -0.60638893 -0.3212306
  -0.24386686 -0.16324644  0.36042239  0.29366232 -0.25993629 -0.1605385
  -0.09750664 -0.10296914 -0.02068216 -0.7466802  -0.54470154 -0.34096594
   0.88149021  0.7459781   1.04608102  1.0329139   1.01793387 -1.0752115
  -1.08166055  1.36156934 -1.36506597  1.36847997  1.35059093 -1.34677083]
 [-0.28957186 -0.6870535  -0.9199063  -0.04082233  5.63022529 -1.52417501
  -0.68535035  0.52236713 -0.39373879 -0.38931178 -0.31304515 -0.12062489
  -0.2101655  -0.77314869 -0.74699287 -0.67996463  0.01939213 -0.1033879
  -0.89719541 -0.82587914 -0.72741018  0.72278193  0.46209728 -0.07682535
  -0.09011024 -0.08221399 -0.06123709 -0.10186308  7.20671833  6.46746505
   4.80836576 -0.27348561 -0.02146196 -1.10674406 -0.71182849 -0.40342646
   2.23163223  2.38761548 -0.69139104 -0.69621697 -0.69978852  0.66979306
   0.66036381 -0.52710018  0.53174616 -0.5363044  -0.51264276  0.50765298]]

6. Train a model including all these features. Do you get better performances than before?

In [26]:
# Train model
print("Train model...")
regressor = LinearRegression()
regressor.fit(X_train, Y_train)
print("...Done.")

Train model...
...Done.

In [27]:
# Predictions on training set
print("Predictions on training set...")
Y_train_pred = regressor.predict(X_train)
print("...Done.")
print(Y_train_pred)
print()

Predictions on training set...
...Done.
[0.81154535 1.38885205 0.90064246 ... 2.38237549 2.48941613 1.28639375]

In [28]:
# Predictions on test set
print("Predictions on test set...")
Y_test_pred = regressor.predict(X_test)
print("...Done.")
print(Y_test_pred)
print()

Predictions on test set...
...Done.
[3.04601756 1.62362395 1.18009908 ... 2.22226679 2.29221063 2.9870925 ]

In [29]:
# Print R^2 scores
print("R2 score on training set : ", r2_score(Y_train, Y_train_pred))
print("R2 score on test set : ", r2_score(Y_test, Y_test_pred))

R2 score on training set :  0.6831497565034788
R2 score on test set :  0.6858617135623264

## Forward selection
This feature engineering trick improved the model's score significantly ! But now, the model is a lot more complex as it uses 32 input features. Do we really need all these features? Let's implement the forward selection method described in this morning's lecture. 

Fortunately, the latest versions of sklearn provide a class that implements forward selection, such that we don't need to code the algorithm by hand 🥳

7. Have a look at the documentation of [SequentialFeatureSelector](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SequentialFeatureSelector.html) and try to understand the following lines of code:

In [30]:
from sklearn.feature_selection import  SequentialFeatureSelector
feature_selector =  SequentialFeatureSelector(regressor, n_features_to_select = 20)
feature_selector.fit(X_train, Y_train)
features_list = X.columns
best_features = features_list[feature_selector.support_]
print("According to the forward selection algorithm, the following features should be kept: ")
print(best_features.to_list())

According to the forward selection algorithm, the following features should be kept:
['MedInc', 'HouseAge', 'Population', 'Latitude', 'MedInc_inverse2', 'AveRooms_3', 'AveRooms_4', 'AveRooms_inverse', 'AveRooms_inverse2', 'AveBedrms_inverse', 'Population_2', 'Population_inverse2', 'AveOccup_3', 'AveOccup_inverse', 'AveOccup_inverse2', 'Latitude_3', 'Latitude_4', 'Latitude_inverse', 'Latitude_inverse2', 'Longitude_inverse']

8. Create a DataFrame X_best containing only the best set of features, train a model only with these features and evaluate the performances

In [31]:
# Separate target variable Y from features X
print("Separating labels from features...")
features_list = best_features.to_list()
target_variable = "Price"

X = data_filtered.loc[:,features_list]
Y = data_filtered.loc[:,target_variable]

print("...Done.")
print()

print('Y : ')
print(Y.head())
print()
print('X :')
print(X.head())

Separating labels from features...
...Done.

Y :
0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
Name: Price, dtype: float64

X :
   MedInc  HouseAge  Population  Latitude  MedInc_inverse2  AveRooms_3  \
0  8.3252      41.0       322.0     37.88         0.014428  340.671954
1  8.3014      21.0      2401.0     37.86         0.014511  242.753076
2  7.2574      52.0       496.0     37.85         0.018986  569.338486
3  5.6431      52.0       558.0     37.85         0.031403  196.868367
4  3.8462      52.0       565.0     37.85         0.067598  247.892488

    AveRooms_4  AveRooms_inverse  AveRooms_inverse2  AveBedrms_inverse  \
0  2379.296184          0.143182           0.020501           0.976744
1  1514.326968          0.160304           0.025697           1.028933
2  4718.754574          0.120654           0.014557           0.931579
3  1145.252511          0.171900           0.029549           0.931915
4  1557.224240          0.159189           0.025341           0.925000

   Population_2  Population_inverse2  AveOccup_3  AveOccup_inverse  \
0      103684.0         9.644690e-06   16.689986          0.391304
1     5764801.0         1.734665e-07    9.391819          0.473969
2      246016.0         4.064776e-06   22.005195          0.356855
3      311364.0         3.211675e-06   16.541323          0.392473
4      319225.0         3.132587e-06   10.381164          0.458407

   AveOccup_inverse2    Latitude_3    Latitude_4  Latitude_inverse  \
0           0.153119  54353.799872  2.058922e+06          0.026399
1           0.224647  54267.751656  2.054577e+06          0.026413
2           0.127345  54224.761625  2.052407e+06          0.026420
3           0.154035  54224.761625  2.052407e+06          0.026420
4           0.210137  54224.761625  2.052407e+06          0.026420

   Latitude_inverse2  Longitude_inverse
0           0.000697          -0.008181
1           0.000698          -0.008182
2           0.000698          -0.008181
3           0.000698          -0.008180
4           0.000698          -0.008180

In [32]:
# Divide dataset Train set & Test set 
print("Dividing into train and test sets...")
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
print("...Done.")
print()

print("Preprocessing X_train...")
print(X_train.head())
print()
preprocessor = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])
X_train = preprocessor.fit_transform(X_train)
print("...Done!")
print(X_train[0:5,:]) # X_train is now a numpy array
print()

# Test pipeline
print("Preprocessing X_test...")
print(X_test.head())
print()
X_test = preprocessor.transform(X_test)
print("...Done!")
print(X_test[0:5,:]) # X_test is now a numpy array
print() 

# Train model
print("Train model...")
regressor = LinearRegression()
regressor.fit(X_train, Y_train)
print("...Done.")

# Predictions on training set
print("Predictions on training set...")
Y_train_pred = regressor.predict(X_train)
print("...Done.")
print(Y_train_pred)
print()

# Predictions on test set
print("Predictions on test set...")
Y_test_pred = regressor.predict(X_test)
print("...Done.")
print(Y_test_pred)
print()

# Print R^2 scores
print("R2 score on training set : ", r2_score(Y_train, Y_train_pred))
print("R2 score on test set : ", r2_score(Y_test, Y_test_pred))

Dividing into train and test sets...
...Done.

Preprocessing X_train...
       MedInc  HouseAge  Population  Latitude  MedInc_inverse2  AveRooms_3  \
3235   2.3889       6.0       992.0     36.09         0.175228  252.030501
13981  3.4912       7.0      2933.0     34.85         0.082045  583.293888
9219   1.9464      36.0       639.0     37.12         0.263959  123.172247
10851  3.1667      22.0      1952.0     33.66         0.099721   55.038428
8888   4.2520      31.0      1985.0     34.03         0.055311   62.963842

        AveRooms_4  AveRooms_inverse  AveRooms_inverse2  AveBedrms_inverse  \
3235   1591.979495          0.158313           0.025063           0.772397
13981  4873.600216          0.119684           0.014324           0.643172
9219    612.844771          0.200984           0.040395           0.949612
10851   209.357262          0.262892           0.069112           1.000000
8888    250.488789          0.251364           0.063184           0.962104

       Population_2  Population_inverse2  AveOccup_3  AveOccup_inverse  \
3235       984064.0         1.016194e-06   30.072045          0.321573
13981     8602489.0         1.162454e-07   15.834621          0.398227
9219       408321.0         2.449054e-06   17.742071          0.383412
10851     3810304.0         2.624463e-07    9.012202          0.480533
8888      3940225.0         2.537926e-07    4.062753          0.626700

       AveOccup_inverse2    Latitude_3    Latitude_4  Latitude_inverse  \
3235            0.103409  47006.795529  1.696475e+06          0.027709
13981           0.158585  42326.109125  1.475065e+06          0.028694
9219            0.147004  51147.440128  1.898593e+06          0.026940
10851           0.230912  38136.631896  1.283679e+06          0.029709
8888            0.392753  39408.131827  1.341059e+06          0.029386

       Latitude_inverse2  Longitude_inverse
3235            0.000768          -0.008363
13981           0.000823          -0.008514
9219            0.000726          -0.008315
10851           0.000883          -0.008482
8888            0.000864          -0.008440

...Done!
[[-0.81992708 -1.808924   -0.41613494  0.21176474  0.18269595  0.80381442
   0.66905388 -0.83350704 -0.61221021 -1.89314156 -0.30593954 -0.02041118
  -0.0341708  -0.44011379 -0.47321997  0.14915531  0.11786383 -0.27348838
  -0.30369805  0.01946793]
 [-0.11259428 -1.72879039  1.40114366 -0.36762209 -0.28361998  3.77972789
   4.19399159 -1.55246631 -0.95692551 -3.27882867  0.74388185 -0.02135856
  -0.4278608   0.40365283  0.26089271 -0.40735174 -0.42544497  0.32382734
   0.30065788 -1.05947081]
 [-1.10387407  0.59508421 -0.74663435  0.69302961  0.6267271  -0.35378714
  -0.38267915 -0.03928915 -0.12004667  0.00714416 -0.38527711 -0.01890281
  -0.37511641  0.2405728   0.10681651  0.64145446  0.61383135 -0.73930427
  -0.76034144  0.3690467 ]
 [-0.32082208 -0.52678629  0.48267364 -0.92364655 -0.19516347 -0.96586912
  -0.81608339  1.11295801  0.80181207  0.54745205  0.08351723 -0.02120465
  -0.61651275  1.30962474  1.22319982 -0.90545682 -0.89507807  0.93844069
   0.94456969 -0.83129194]
 [ 0.37560203  0.19441617  0.51357019 -0.75076499 -0.41740151 -0.89467095
  -0.77190215  0.89838722  0.61150001  0.14108805  0.10142038 -0.02121376
  -0.75337379  2.91854846  3.37649337 -0.75428269 -0.75427664  0.74273764
   0.73711017 -0.5279845 ]]

Preprocessing X_test...
       MedInc  HouseAge  Population  Latitude  MedInc_inverse2  AveRooms_3  \
17333  5.2990      12.0      1200.0     34.91         0.035613  375.575064
1012   2.6667      44.0       277.0     37.68         0.140621   93.656107
5124   1.5521      30.0      1966.0     33.99         0.415108   57.096812
1845   6.3538      49.0      1148.0     37.90         0.024770  249.319665
4035   3.2154      20.0      7450.0     34.17         0.096723   70.621393

        AveRooms_4  AveRooms_inverse  AveRooms_inverse2  AveBedrms_inverse  \
17333  2709.748594          0.138601           0.019210           0.954644
1012    425.319019          0.220202           0.048489           0.973214
5124    219.861479          0.259694           0.067441           0.997743
1845   1569.189449          0.158884           0.025244           0.982558
4035    291.909598          0.241929           0.058530           0.943235

       Population_2  Population_inverse2  AveOccup_3  AveOccup_inverse  \
17333     1440000.0         6.944444e-07   20.011375          0.368333
1012        76729.0         1.303288e-05   16.411936          0.393502
5124      3865156.0         2.587218e-07   88.000215          0.224822
1845      1317904.0         7.587806e-07   11.609186          0.441638
4035     55502500.0         1.801721e-08    5.565199          0.564295

       AveOccup_inverse2    Latitude_3    Latitude_4  Latitude_inverse  \
17333           0.135669  42545.099771  1.485249e+06          0.028645
1012            0.154844  53497.400832  2.015782e+06          0.026539
5124            0.050545  39269.330199  1.334765e+06          0.029420
1845            0.195044  54439.939000  2.063274e+06          0.026385
4035            0.318429  39896.512713  1.363264e+06          0.029265

       Latitude_inverse2  Longitude_inverse
17333           0.000821          -0.008303
1012            0.000704          -0.008212
5124            0.000866          -0.008456
1845            0.000696          -0.008178
4035            0.000856          -0.008437

...Done!
[[ 1.04744947 -1.32812236 -0.22139308 -0.33958724 -0.5159755   1.9136803
   1.86970038 -1.20037727 -0.80008105  0.06109415 -0.24311142 -0.02074989
  -0.31236615  0.07460051 -0.04399513 -0.381315   -0.40045361  0.29394803
   0.2699244   0.45333115]
 [-0.64166613  1.23615306 -1.08556008  0.95468818  0.00951432 -0.61894617
  -0.58410907  0.31839396  0.13978309  0.26022794 -0.4309706  -0.00776121
  -0.41189701  0.35163994  0.21111713  0.92085146  0.90139632 -0.9818765
  -0.99304936  1.10461025]
 [-1.35689169  0.11428257  0.49578127 -0.76945489  1.38311784 -0.94737757
  -0.80480034  1.05343787  0.74816593  0.52324656  0.09107585 -0.02120857
   1.56764567 -1.50508639 -1.17657331 -0.77078542 -0.76972167  0.76368932
   0.75921207 -0.64586306]
 [ 1.72430209  1.6368211  -0.27007855  1.05748262 -0.57023635  0.77946155
   0.64457406 -0.82286628 -0.60638893  0.36042239 -0.25993629 -0.02068216
  -0.54470154  0.88149021  0.7459781   1.0329139   1.01793387 -1.0752115
  -1.08166055  1.35059093]
 [-0.28957186 -0.6870535   5.63022529 -0.68535035 -0.2101655  -0.82587914
  -0.72741018  0.72278193  0.46209728 -0.06123709  7.20671833 -0.02146196
  -0.71182849  2.23163223  2.38761548 -0.69621697 -0.69978852  0.66979306
   0.66036381 -0.51264276]]

Train model...
...Done.
Predictions on training set...
...Done.
[0.7773865  1.50358473 0.88237034 ... 2.27318551 2.41252783 1.30387105]

Predictions on test set...
...Done.
[3.04288607 1.70795136 1.01982206 ... 2.27610954 2.27690312 3.06956596]

R2 score on training set :  0.664114119822615
R2 score on test set :  0.6727171115611735

## Advanced feature engineering
Let's make even more advanced feature engineering. Until now, we've included the latitude and longitude as such into the models. However, usually the GPS coordinates are not used rawly, instead we deduce some geographical information from these. Let's use an API that will allows to retrieve the name of the city from the latitude and longitude.

💡 As the calls to the API may be time-consuming, we'll work on a sample of the dataset.

9. Take a sample of your dataset X (the one that contains all the features and not only the best set, because we need the values of Latitude and Longitude). Keep only 150 rows.

In [36]:
# Separate target variable Y from features X
print("Separating labels from features...")
features_list = data_filtered.drop("Price", axis=1).columns.tolist()
target_variable = "Price"

X_sample = data_filtered.loc[:150,features_list]
Y_sample = data_filtered.loc[:150,target_variable]

print("...Done.")
print()

print('Y : ')
print(Y_sample.head())
print()
print('X :')
print(X_sample.head())

Separating labels from features...
...Done.

Y :
0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
Name: Price, dtype: float64

X :
   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85

   Longitude   MedInc_2    MedInc_3  ...  Latitude_2    Latitude_3  \
0    -122.23  69.308955  577.010912  ...   1434.8944  54353.799872
1    -122.22  68.913242  572.076387  ...   1433.3796  54267.751656
2    -122.24  52.669855  382.246204  ...   1432.6225  54224.761625
3    -122.25  31.844578  179.702136  ...   1432.6225  54224.761625
4    -122.25  14.793254   56.897815  ...   1432.6225  54224.761625

     Latitude_4  Latitude_inverse  Latitude_inverse2  Longitude_2  \
0  2.058922e+06          0.026399           0.000697   14940.1729
1  2.054577e+06          0.026413           0.000698   14937.7284
2  2.052407e+06          0.026420           0.000698   14942.6176
3  2.052407e+06          0.026420           0.000698   14945.0625
4  2.052407e+06          0.026420           0.000698   14945.0625

    Longitude_3   Longitude_4  Longitude_inverse  Longitude_inverse2
0 -1.826137e+06  2.232088e+08          -0.008181            0.000067
1 -1.825689e+06  2.231357e+08          -0.008182            0.000067
2 -1.826586e+06  2.232818e+08          -0.008181            0.000067
3 -1.827034e+06  2.233549e+08          -0.008180            0.000067
4 -1.827034e+06  2.233549e+08          -0.008180            0.000067

[5 rows x 48 columns]

10. Create a Y_sample variable containing the target values corresponding to the rows that were kept in X_sample

1523     3.068
2704     0.675
2047     1.272
11174    2.052
1763     1.341
Name: Price, dtype: float64

11. Use the following help to translate the longitude and latitude of the data to find the cities corresponding to each observation: [geopy](https://pypi.org/project/geopy)

In [35]:
!pip install geopy

Collecting geopy
  Downloading geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.1-py3-none-any.whl.metadata (1.6 kB)
Downloading geopy-2.4.1-py3-none-any.whl (125 kB)
Downloading geographiclib-2.1-py3-none-any.whl (40 kB)
Installing collected packages: geographiclib, geopy

   -------------------- ------------------- 1/2 [geopy]
   ---------------------------------------- 2/2 [geopy]

Successfully installed geographiclib-2.1 geopy-2.4.1

In [37]:
# Example of how to get the adress from a given pair of latitude/longitude coordinates
from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent="yet_another_app")
location = geolocator.reverse("52.509669, 13.376294")
loc_dict = dict(location.raw)
loc_dict["address"]

{'house_number': '11',
 'road': 'Potsdamer Platz',
 'suburb': 'Tiergarten',
 'borough': 'Mitte',
 'city': 'Berlin',
 'ISO3166-2-lvl4': 'DE-BE',
 'postcode': '10785',
 'country': 'Deutschland',
 'country_code': 'de'}

In [38]:
# Use geopy to extract the city of each row in the sample dataset
X_sample["City"] = 0
for i, row in X_sample.iterrows():
    geolocator = Nominatim(user_agent="yet_another_app_2")
    location = geolocator.reverse("{}, {}".format(X_sample.loc[i, "Latitude"], X_sample.loc[i, "Longitude"]), 
                                  timeout = None)
    loc_dict = dict(location.raw)
    try:
        X_sample.loc[i, "City"] = loc_dict["address"]["city"]
    except:
        try:
            X_sample.loc[i, "City"] = loc_dict["address"]["town"]
        except:
            try:
                X_sample.loc[i, "City"] = loc_dict["address"]["village"]
            except:
                pass
# If city was not found, replace by "Unknown"
X_sample.loc[X_sample['City'] == 0, 'City'] = "Unknown"

C:\Users\briic\AppData\Local\Temp\ipykernel_24664\1970226461.py:9: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Oakland' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

In [39]:
X_sample.describe(include='all')

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedInc_2,MedInc_3,...,Latitude_3,Latitude_4,Latitude_inverse,Latitude_inverse2,Longitude_2,Longitude_3,Longitude_4,Longitude_inverse,Longitude_inverse2,City
count,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,...,149.000000,1.490000e+02,149.000000,1.490000e+02,149.000000,1.490000e+02,1.490000e+02,149.000000,1.490000e+02,149
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Oakland
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137
mean,3.218595,43.000000,4.970076,1.081219,900.335570,2.379286,37.825503,-122.255705,15.106081,91.351659,...,54119.577559,2.047101e+06,0.026437,6.989254e-04,14946.458117,-1.827290e+06,2.233967e+08,-0.008180,6.690550e-05,NaN
std,2.186047,11.585172,1.382896,0.122885,573.607392,0.549293,0.016621,0.028123,20.474284,185.439747,...,71.352277,3.598806e+03,0.000012,6.141275e-07,6.875713,1.260782e+03,2.054991e+05,0.000002,3.078887e-08,NaN
min,0.499900,2.000000,1.714286,0.571429,18.000000,1.437141,37.790000,-122.300000,0.249900,0.124925,...,53967.298139,2.039424e+06,0.026399,6.969154e-04,14927.952400,-1.829277e+06,2.228438e+08,-0.008185,6.685703e-05,NaN
25%,1.687500,36.000000,3.980237,1.023810,534.000000,2.101083,37.810000,-122.280000,2.847656,4.805420,...,54053.028541,2.043745e+06,0.026427,6.983896e-04,14942.617600,-1.828379e+06,2.232818e+08,-0.008181,6.687890e-05,NaN
50%,2.600000,49.000000,4.797980,1.068000,756.000000,2.346154,37.820000,-122.260000,6.760000,17.576000,...,54095.927768,2.045908e+06,0.026441,6.991284e-04,14947.507600,-1.827482e+06,2.234280e+08,-0.008179,6.690079e-05,NaN
75%,3.964300,52.000000,6.047244,1.114943,1129.000000,2.606880,37.840000,-122.240000,15.715674,62.301648,...,54181.794304,2.050239e+06,0.026448,6.994983e-04,14952.398400,-1.826586e+06,2.235742e+08,-0.008178,6.692268e-05,NaN
max,11.601700,52.000000,8.335052,1.659864,3469.000000,5.617647,37.880000,-122.180000,134.599443,1561.582357,...,54353.799872,2.058922e+06,0.026462,7.002389e-04,14957.290000,-1.823897e+06,2.237205e+08,-0.008177,6.698842e-05,NaN

12. Make a train/test splitting from X_sample and Y_sample

In [49]:
# Divide dataset Train set & Test set 
print("Dividing into train and test sets...")
X_train, X_test, Y_train, Y_test = train_test_split(X_sample, Y_sample, test_size=0.2, random_state=0)
print("...Done.")
print()

Dividing into train and test sets...
...Done.

13. What preprocessings are necessary now ? The cells below implement the preprocessings, read it carefully and check what is done

In [50]:
categorical_features = ['City']
numeric_features = [c for c in X_sample.columns if c != 'City']

In [51]:
print(categorical_features)
print(numeric_features)

['City']
['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude', 'MedInc_2', 'MedInc_3', 'MedInc_4', 'MedInc_inverse', 'MedInc_inverse2', 'HouseAge_2', 'HouseAge_3', 'HouseAge_4', 'HouseAge_inverse', 'HouseAge_inverse2', 'AveRooms_2', 'AveRooms_3', 'AveRooms_4', 'AveRooms_inverse', 'AveRooms_inverse2', 'AveBedrms_2', 'AveBedrms_3', 'AveBedrms_4', 'AveBedrms_inverse', 'AveBedrms_inverse2', 'Population_2', 'Population_3', 'Population_4', 'Population_inverse', 'Population_inverse2', 'AveOccup_2', 'AveOccup_3', 'AveOccup_4', 'AveOccup_inverse', 'AveOccup_inverse2', 'Latitude_2', 'Latitude_3', 'Latitude_4', 'Latitude_inverse', 'Latitude_inverse2', 'Longitude_2', 'Longitude_3', 'Longitude_4', 'Longitude_inverse', 'Longitude_inverse2']

In [52]:
# Create transformer for numeric features
numeric_transformer = StandardScaler()

In [53]:
# Create transformer for categorical features
categorical_transformer = OneHotEncoder(drop='first', handle_unknown = 'ignore') # ignore if unknown categories are found in test set

In [54]:
# Use ColumnTransformer to make a preprocessor object that describes all the treatments to be done
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

In [55]:
# Preprocessings on train set
print("Performing preprocessings on train set...")
X_train = preprocessor.fit_transform(X_train)
print('...Done.')

# Preprocessings on test set
print("Performing preprocessings on test set...")
X_test = preprocessor.transform(X_test) # Don't fit again !! The test set is used for validating decisions
# we made based on the training set, therefore we can only apply transformations that were parametered using the training set.
# Otherwise this creates what is called a leak from the test set which will introduce a bias in all your results.
print('...Done.')

Performing preprocessings on train set...
...Done.
Performing preprocessings on test set...
...Done.

c:\Users\briic\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning:

Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros

14. Train a regression model and evaluate the performances. Are you satisfied?

In [56]:
# Train model
print("Train model...")
regressor = LinearRegression()
regressor.fit(X_train, Y_train)
print("...Done.")

Y_train_pred = regressor.predict(X_train)
Y_test_pred = regressor.predict(X_test)

# Print R^2 scores
print("R2 score on training set : ", r2_score(Y_train, Y_train_pred))
print("R2 score on test set : ", r2_score(Y_test, Y_test_pred))

Train model...
...Done.
R2 score on training set :  0.9534395615489626
R2 score on test set :  -7037.193761855995